version: '3.6'

services:

  root-ocsp:
    build: ./ocsp
    ports:
      - "2552:2552"
    volumes:
      - ./root_ca/index.txt:/opt/ocsp/index.txt
      - ./root_ca/certs/root_ca_cert.pem:/opt/ocsp/ca-chain.pem
      - ./root_ca/private/root_ca_ocsp_key.pem:/opt/ocsp/key.pem
      - ./root_ca/certs/root_ca_ocsp_cert.pem:/opt/ocsp/cert.pem

  ocsp:
    build: ./ocsp
    ports:
      - "2553:2552"
    volumes:
      - ./issuing_ca/index.txt:/opt/ocsp/index.txt
      - ./issuing_ca/certs/ca_chain.pem:/opt/ocsp/ca-chain.pem
      - ./issuing_ca/private/issuing_ca_ocsp_key.pem:/opt/ocsp/key.pem
      - ./issuing_ca/certs/issuing_ca_ocsp_cert.pem:/opt/ocsp/cert.pem

  cert-dir:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/servers/cert-dir.conf:/etc/nginx/my-conf.d/cert-dir.conf
      - ./root_ca/certs/root_ca_cert.der:/var/www/cert-dir/root-ca.crt
      - ./root_ca/crl/crl.der:/var/www/cert-dir/root-ca.crl
      - ./issuing_ca/certs/issuing_ca_cert.der:/var/www/cert-dir/issuing-ca.crt
      - ./issuing_ca/crl/crl.der:/var/www/cert-dir/issuing-ca.crl

  example1.com:
    image: nginx
    ports:
      - "8443:443"
    links:
      - "cert-dir"
      - "ocsp"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/servers/example.com.conf:/etc/nginx/my-conf.d/example.com.conf
      - ./nginx/web/index.html:/var/www/example.com/index.html
      - ./server/certs/example1.com.cert.pem:/var/www/certs/example.com.cert.pem
      - ./server/private/example1.com.key.pem:/var/www/certs/example.com.key.pem
      - ./issuing_ca/certs/ca_chain.pem:/var/www/certs/ca-chain.pem
      - ./issuing_ca/crl/combined_crl.pem:/var/www/certs/crl.pem

  example2.com:
    image: httpd
    ports:
      - "8082:80"
      - "8444:443"
    hostname: example2.com
    links:
      - "cert-dir"
      - "ocsp"
    volumes:
      - ./httpd/web/index.html:/usr/local/apache2/htdocs/index.html
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
      - ./server/certs/example2.com.cert.pem:/usr/local/apache2/conf/server.crt
      - ./server/private/example2.com.key.pem:/usr/local/apache2/conf/server.key
      - ./issuing_ca/certs/ca_chain.pem:/usr/local/apache2/conf/server-ca.crt
      - ./issuing_ca/certs/ca_chain.pem:/usr/local/apache2/conf/ssl.crt/ca-bundle.crt
      - ./issuing_ca/crl/combined_crl.pem:/usr/local/apache2/conf/ssl.crl/ca-bundle.crl

